### ISSUE TITLE
Group Dynamics/Cabinet: VRCPhysBone Scripts Not Properly Enabled When Switching Outfits in Cabinet

### ISSUE THREAD

**Issue by CuteLuoBo** [poi-vrc/DressingTools#407] opened 2024-04-21 09:10 UTC
**Translated content：**

Problem Description:
When using the "Cabinet" feature of the DressingTools plugin to switch between different outfits, an issue is found - although the newly switched outfit is correctly loaded, the physics simulation scripts (such as VRCPhysBone) under the DT_Dynamics hierarchy are not automatically enabled, causing the new outfit to not have the correct physics simulation effects.

Expected Behavior:
When switching to a new outfit from the wardrobe, the VRC Phys Bone scripts related to that outfit should be automatically enabled to ensure that the physics simulation works correctly.

Reproduction Steps:

Import outfit prefabs (unzipped) containing dynamics effects into the DressingTools wardrobe, adjust the bone mapping (the bone node names in the clothing prefab do not completely match the original model), use "Auto/Retain Worn Item Bones xxx", and add to the wardrobe.
Use the Gesture Manager for testing, select the wardrobe menu, and switch outfits.
Observe that the clothing model's dynamics are not working correctly, and check that the physics simulation scripts (such as VRCPhysBone) under the DT_Dynamics hierarchy are still disabled.
Relevant Environment:

Unity version: unity 2022.3.6f1
DressingTools version: 2.4.0

![QQ截图20240421162914](https://github.com/poi-vrc/DressingTools/assets/44561136/4c6fa2e4-f286-4a9f-ac13-8b92d3ba29cc)
![QQ截图20240421163108](https://github.com/poi-vrc/DressingTools/assets/44561136/4fbd6f6f-6553-4489-8309-1156e91e4890)
![QQ截图20240421163233](https://github.com/poi-vrc/DressingTools/assets/44561136/6e0db5a1-87bb-48c2-baf1-98881329232f)
![QQ截图20240421163307](https://github.com/poi-vrc/DressingTools/assets/44561136/2efa9e8e-904a-4ff8-b701-50143f15b4e1)

**Comment by CuteLuoBo** [comment] 2024-04-21 10:53
Sorry, I didn't notice there was an option to disable the clothing dynamics by default. After testing with that option turned off, it works normally now.

setWearableDynamicsInactive - 將穿戴物品動骨設定為關閉狀態
![QQ截图20240421184743](https://github.com/poi-vrc/DressingTools/assets/44561136/50d8c181-d248-4a32-89cb-3ed39be6a482)

**Comment by poi-vrc** [comment] 2024-04-21 10:58
Yup, you could disable this feature to not disable any dynamics at all. But it could become a performance and physbone interaction issue if you keep them all on. You can roll-back to use v2.3 which probably does not have the bug.
Would you mind if I contact you privately or here later on to roll out a fix for this? Because this is not an expected behaviour.

**Comment by CuteLuoBo** [comment] 2024-04-21 11:22
> Yup, you could disable this feature to not disable any dynamics at all. But it could become a performance and physbone interaction issue (people might grab invisible unrelated bones) if you keep them all on. If you want to use it right now, I prefer you can roll-back to use v2.3 which probably does not have the bug.
> 
> Would you mind if I contact you privately or here later on to roll out a fix for this? Because this is not an expected behaviour. You can join the discord server https://discord.gg/Gyst8Pr2ay and I can pm privately. I can speak in Chinese (Mandarin and Cantonese) if you want to.

I will try the 2.3.0 version and see if it improves the issue. I plan to go for some entertainment on VRChat tonight, so if any other testing is needed, it will likely be very late or tomorrow. I hope you don't mind.

**Comment by poi-vrc** [comment] 2024-04-21 15:50
Sorry for late reply since I just ended work. I can confirm the issue, and I am surprised why I missed it. I will migrate it immediately.

**Closed** 2024-04-21 16:11 UTC
